#! /bin/bash

curl http://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getAccountInfo",
    "params": [
      "APNL6fUKDq5XKGxmdAE1LYbSWNNsVbfTFUhvEnt6toVx",
      {
        "encoding": "jsonParsed"
      }
    ]
  }
'