[features]
seeds = true
skip-lint = false
[programs.localnet]
candy_box = "CD8QX7UQSSHWzKbZbMGVbqVnGqiJWqupjdDMHwyvchbR"

[programs.devnet]
candy_box = "CD8QX7UQSSHWzKbZbMGVbqVnGqiJWqupjdDMHwyvchbR"

[programs.testnet]
candy_box = "CD8QX7UQSSHWzKbZbMGVbqVnGqiJWqupjdDMHwyvchbR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "tests/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
